name: Nightly NHS Scrape

on:
  schedule:
    # Run every day at 20:00 UK time (handles BST/GMT automatically)
    - cron: "0 20 * * *"
      timezone: "Europe/London"
  workflow_dispatch: {}   # allow manual run from the Actions tab

permissions:
  contents: write   # needed to commit updated data files back to the repo

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run NHS scraper
        run: npx ts-node ./smilemap-web/scripts/scrape-nhs.ts

      # OPTIONAL: if your scraper writes into outputs/ and you want those changes
      # to appear on your site (because your Next app reads from outputs/), then commit them.
      - name: Commit & push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "chore(data): nightly NHS scrape"
            git push
          fi
